# Generated by Django 2.2.26 on 2022-03-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('PlaceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_type', models.CharField(max_length=128)),
                ('place_name', models.CharField(max_length=150)),
                ('place_map', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('saved', models.BooleanField(default=False)),
                ('PlaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Place', verbose_name='the related place')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile', verbose_name='the user')),
            ],
            options={
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('PlaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Place', verbose_name='the related place')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile', verbose_name='the user')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
    ]
