# Generated by Django 2.1.5 on 2022-03-26 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('PlaceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Fast Food', 'Fast Food'), ('Nightlife', 'Nightlife'), ('Anywhere', 'Anywhere')], max_length=128)),
                ('place_name', models.CharField(max_length=150)),
                ('place_image', models.ImageField(blank=True, default='/place_images/Default.jpg', upload_to='place_images')),
                ('latitude', models.CharField(blank=True, default=0, max_length=25, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, default=0, max_length=25, verbose_name='longitude')),
                ('url', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('dislikes', models.ManyToManyField(related_name='place_dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='place_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saves', models.ManyToManyField(related_name='place_save', to='rango.Place')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='PlaceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Place', verbose_name='the related place'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user'),
        ),
    ]
