# Generated by Django 2.2.26 on 2022-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(default='/place_images/Default.jpg', upload_to='place_images'),
        ),
    ]
