# Generated by Django 2.2.26 on 2022-03-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('PlaceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_type', models.CharField(max_length=128)),
                ('place_name', models.CharField(max_length=150)),
                ('place_map', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('saved', models.BooleanField(default=False)),
                ('PlaceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Place', verbose_name='the related place')),
            ],
            options={
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile', verbose_name='the user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='PlaceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Place', verbose_name='the related place'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile', verbose_name='the user'),
        ),
    ]
