# Generated by Django 2.2.26 on 2022-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Fast Food', 'Fast Food'), ('Nightlife', 'Nightlife')], max_length=128),
        ),
    ]
