# Generated by Django 2.2.26 on 2022-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saves',
            field=models.ManyToManyField(related_name='place_save', to='rango.Place'),
        ),
    ]
