# Generated by Django 2.2.26 on 2022-03-23 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0002_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved',
            field=models.ManyToManyField(default=[], related_name='_userprofile_saved_+', to='rango.UserProfile'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Fast Food', 'Fast Food'), ('Nightlife', 'Nightlife')], max_length=128),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='SavedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedList', to='rango.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LikeButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('saved_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.SavedList')),
            ],
        ),
    ]
