# Generated by Django 2.2.26 on 2022-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220327_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Fast Food', 'Fast Food'), ('Nightlife', 'Nightlife'), ('Anywhere', 'Anywhere')], max_length=128),
        ),
    ]
