# Generated by Django 2.2.26 on 2022-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220325_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Cafes', 'Cafes'), ('Fast Food', 'Fast Food'), ('Nightlife', 'Nightlife'), ('Anywhere', 'Anywhere')], max_length=128),
        ),
    ]
