# Generated by Django 2.2.26 on 2022-03-25 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_userprofile_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dislikes',
            field=models.ManyToManyField(default=[], related_name='place_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(default=[], related_name='place_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
