# Generated by Django 2.2.26 on 2022-03-25 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220325_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dislikes',
            field=models.ManyToManyField(related_name='place_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, default=0, max_length=25, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(related_name='place_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, default=0, max_length=25, verbose_name='longitude'),
        ),
    ]
