# Generated by Django 2.2.26 on 2022-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220325_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='defaultName', max_length=150),
            preserve_default=False,
        ),
    ]
