# Generated by Django 2.2.26 on 2022-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220326_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
