# Generated by Django 2.2.26 on 2022-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
