# Generated by Django 2.2.26 on 2022-03-23 12:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20220323_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='savedlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=[], related_name='_userprofile_disliked_+', to='rango.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked',
            field=models.ManyToManyField(blank=True, default=[], related_name='_userprofile_liked_+', to='rango.UserProfile'),
        ),
        migrations.AlterField(
            model_name='place',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='place',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved',
            field=models.ManyToManyField(blank=True, default=[], related_name='_userprofile_saved_+', to='rango.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavedList',
        ),
    ]
