# Generated by Django 2.2.26 on 2022-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20220323_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_list', to='rango.Place'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_list', to='rango.Place'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_list', to='rango.Place'),
        ),
    ]
