# Generated by Django 2.2.26 on 2022-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20220325_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(blank=True, default='Default image.jpg', upload_to='place_images'),
        ),
    ]
