# Generated by Django 2.2.26 on 2022-03-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20220323_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
