# Generated by Django 2.2.26 on 2022-03-23 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0007_auto_20220323_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='likes',
        ),
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(related_name='place_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
