# Generated by Django 2.2.26 on 2022-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20220323_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.ImageField(blank=True, upload_to='place_images'),
        ),
    ]
