# Generated by Django 2.2.26 on 2022-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_remove_userprofile_name'),
        ('rango', '0008_auto_20220325_1536'),
    ]

    operations = [
    ]
