# Generated by Django 2.2.26 on 2022-03-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_place_place_image'),
        ('rango', '0010_auto_20220324_1352'),
    ]

    operations = [
    ]
