# Generated by Django 2.2.26 on 2022-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_merge_20220324_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_map',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='longitude'),
        ),
    ]
