# Generated by Django 2.2.26 on 2022-03-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20220324_1502'),
        ('rango', '0012_auto_20220324_1452'),
    ]

    operations = [
    ]
